#!/usr/bin/env python3
"""Collect a read-only repository inventory for incremental project updates."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
from itertools import islice
from pathlib import Path
from typing import Any


SKIPPED_DIRECTORIES = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "vendor",
}
INSTRUCTION_NAMES = {"AGENTS.md", "CLAUDE.md"}
CONFIG_NAMES = {
    ".gitignore",
    "Makefile",
    "package.json",
    "openai.yaml",
    "openai.yml",
    "pyproject.toml",
    "requirements.txt",
    "setup.cfg",
    "tox.ini",
    "tsconfig.json",
}
TEXT_SUFFIXES = {
    ".css",
    ".go",
    ".html",
    ".java",
    ".js",
    ".json",
    ".jsx",
    ".md",
    ".py",
    ".rb",
    ".rs",
    ".sh",
    ".sql",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".yaml",
    ".yml",
}
GENERATED_MARKERS = (
    "auto-generated",
    "autogenerated",
    "do not edit",
    "generated file",
    "generated;",
)
FINGERPRINT_METHOD = "git-head+binary-diff+untracked-content-v1"
COMMENT_PREFIXES = {
    ".css": ("/*",),
    ".go": ("//", "/*"),
    ".html": ("<!--",),
    ".java": ("//", "/*"),
    ".js": ("//", "/*"),
    ".jsx": ("//", "/*"),
    ".md": ("<!--",),
    ".py": ("#",),
    ".rb": ("#",),
    ".rs": ("//", "/*"),
    ".sh": ("#",),
    ".sql": ("--", "/*"),
    ".ts": ("//", "/*"),
    ".tsx": ("//", "/*"),
    ".yaml": ("#",),
    ".yml": ("#",),
}


def relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def repository_files(root: Path) -> tuple[list[Path], list[str]]:
    files: list[Path] = []
    skipped_symlinks: list[str] = []
    for path in sorted(root.rglob("*")):
        parts = path.relative_to(root).parts
        if any(part in SKIPPED_DIRECTORIES for part in parts):
            continue
        if path.is_symlink():
            skipped_symlinks.append(relative(path, root))
            continue
        if path.is_file():
            files.append(path)
    return files, skipped_symlinks


def has_part(path: Path, *names: str) -> bool:
    lowered = {part.lower() for part in path.parts}
    return any(name in lowered for name in names)


def looks_like_test(path: Path) -> bool:
    name = path.name.lower()
    return (
        has_part(path, "test", "tests", "spec", "specs", "__tests__")
        or name.startswith("test_")
        or ".test." in name
        or ".spec." in name
    )


def looks_like_schema(path: Path) -> bool:
    name = path.name.lower()
    return (
        has_part(path, "schema", "schemas")
        or name in {"schema.json", "schema.yaml", "schema.yml"}
        or name.endswith((".schema.json", ".schema.yaml", ".schema.yml"))
    )


def looks_like_config(path: Path) -> bool:
    parts = tuple(part.lower() for part in path.parts)
    in_github_workflows = any(
        parts[index : index + 2] == (".github", "workflows")
        for index in range(len(parts) - 1)
    )
    return path.name in CONFIG_NAMES or has_part(path, "config", "configs") or in_github_workflows


def generated_file(path: Path) -> bool:
    if path.suffix.lower() not in TEXT_SUFFIXES and path.name != "Makefile":
        return False
    try:
        with path.open(encoding="utf-8", errors="ignore") as handle:
            lines = [line.strip().lower() for line in islice(handle, 8) if line.strip()]
    except OSError:
        return False
    prefixes = COMMENT_PREFIXES.get(path.suffix.lower(), ("#",))
    return any(
        line.startswith(prefixes) and any(marker in line for marker in GENERATED_MARKERS)
        for line in lines
    )


def explicit_commands(root: Path) -> list[str]:
    commands: set[str] = set()
    package_json = root / "package.json"
    if package_json.is_file():
        try:
            scripts = json.loads(package_json.read_text(encoding="utf-8")).get("scripts", {})
            if isinstance(scripts, dict):
                commands.update(f"npm run {name}" for name in scripts if isinstance(name, str))
        except (OSError, json.JSONDecodeError, AttributeError):
            pass

    makefile = root / "Makefile"
    if makefile.is_file():
        try:
            for line in makefile.read_text(encoding="utf-8", errors="ignore").splitlines():
                match = re.match(r"^([A-Za-z0-9_.-]+):(?:\s|$)", line)
                if match and not match.group(1).startswith("."):
                    commands.add(f"make {match.group(1)}")
        except OSError:
            pass
    return sorted(commands)


def git_command(root: Path, *args: str, text: bool = False) -> subprocess.CompletedProcess[Any]:
    return subprocess.run(
        ["git", "-C", str(root), *args],
        text=text,
        capture_output=True,
        check=False,
    )


def worktree_fingerprint(root: Path, head: str | None) -> str | None:
    digest = hashlib.sha256()
    digest.update(b"project-evolution-engine-worktree-v1\0")
    digest.update((head or "UNBORN").encode("ascii"))

    if head:
        diff = git_command(root, "diff", "--no-color", "--binary", "--no-ext-diff", "--no-textconv", head, "--", ".")
        listed = git_command(root, "ls-files", "--others", "--exclude-standard", "-z", "--", ".")
        if diff.returncode != 0 or listed.returncode != 0:
            return None
        digest.update(b"\0tracked-diff\0")
        digest.update(diff.stdout)
        path_kind = b"untracked"
    else:
        listed = git_command(root, "ls-files", "--cached", "--others", "--exclude-standard", "-z", "--", ".")
        if listed.returncode != 0:
            return None
        path_kind = b"unborn-file"

    for raw_path in sorted(filter(None, listed.stdout.split(b"\0"))):
        path = root / os.fsdecode(raw_path)
        if path.is_symlink():
            continue
        try:
            content_digest = hashlib.sha256(path.read_bytes()).digest()
        except OSError:
            return None
        digest.update(b"\0" + path_kind + b"\0")
        digest.update(raw_path)
        digest.update(b"\0")
        digest.update(content_digest)

    return f"sha256:{digest.hexdigest()}"


def git_evidence(root: Path) -> dict[str, Any]:
    probe = git_command(root, "rev-parse", "--show-toplevel", text=True)
    if probe.returncode != 0:
        return {
            "is_repository": False,
            "root": None,
            "status": [],
            "head": None,
            "branch": None,
            "dirty": False,
            "worktree_fingerprint": None,
            "fingerprint_method": None,
        }

    status = git_command(root, "status", "--short", "--branch", "--", ".", text=True)
    status_lines = status.stdout.splitlines() if status.returncode == 0 else []
    head_result = git_command(root, "rev-parse", "--verify", "HEAD", text=True)
    branch_result = git_command(root, "symbolic-ref", "--short", "-q", "HEAD", text=True)
    head = head_result.stdout.strip() if head_result.returncode == 0 else None
    branch = branch_result.stdout.strip() if branch_result.returncode == 0 else None
    fingerprint = worktree_fingerprint(root, head)
    return {
        "is_repository": True,
        "root": probe.stdout.strip(),
        "status": status_lines,
        "head": head,
        "branch": branch,
        "dirty": any(line.strip() and not line.startswith("##") for line in status_lines),
        "worktree_fingerprint": fingerprint,
        "fingerprint_method": FINGERPRINT_METHOD if fingerprint else None,
    }


def collect_evidence(root: Path) -> dict[str, Any]:
    root = root.expanduser().resolve()
    if not root.is_dir():
        raise ValueError(f"repository root is not a directory: {root}")

    files, skipped_symlinks = repository_files(root)
    rel = {path: relative(path, root) for path in files}

    inventory = {
        "instruction_files": sorted(value for path, value in rel.items() if path.name in INSTRUCTION_NAMES),
        "domain_files": sorted(value for path, value in rel.items() if path.name == "CONTEXT.md"),
        "adr_files": sorted(
            value
            for path, value in rel.items()
            if path.suffix.lower() == ".md" and has_part(path.relative_to(root), "adr", "adrs")
        ),
        "markdown_files": sorted(value for path, value in rel.items() if path.suffix.lower() == ".md"),
        "test_files": sorted(value for path, value in rel.items() if looks_like_test(path.relative_to(root))),
        "config_files": sorted(
            value
            for path, value in rel.items()
            if looks_like_config(path.relative_to(root))
        ),
        "schema_files": sorted(
            value for path, value in rel.items() if looks_like_schema(path.relative_to(root))
        ),
        "migration_files": sorted(
            value for path, value in rel.items() if has_part(path.relative_to(root), "migration", "migrations")
        ),
        "generated_files": sorted(value for path, value in rel.items() if generated_file(path)),
    }

    return {
        "schema_version": 2,
        "root": str(root),
        "git": git_evidence(root),
        "coverage": {
            "files_seen": len(files),
            "skipped_symlinks": sorted(skipped_symlinks),
        },
        "inventory": inventory,
        "available_commands": explicit_commands(root),
        "limitations": [
            "Inventory is evidence, not a decision about canonical ownership or correctness.",
            "Generated-file detection uses header markers and may miss unmarked artifacts.",
            "The worktree fingerprint identifies Git-visible content; it is not an immutable snapshot or correctness proof.",
            "The fingerprint excludes ignored files, skipped symlinks, submodule internals, artifacts outside the collected root, and external runtime state.",
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True, help="Repository root to inspect")
    parser.add_argument("--pretty", action="store_true", help="Indent JSON output")
    args = parser.parse_args()

    try:
        evidence = collect_evidence(args.root)
    except ValueError as error:
        parser.error(str(error))
    print(json.dumps(evidence, ensure_ascii=False, indent=2 if args.pretty else None, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
